In [1]:
import numpy as np

In [3]:
# This method returns evenly spaced values within an interval. Values are generated within the half open interval. 
# The start value is inclusive and the stop one is exclusive. 
# The format is np.arange(start,stop,step). Where the step value is not included, python uses a step of one.
# The data type could also be given but when not given python uses one like the data given.
np.arange(1,50,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [10]:
# This Return evenly spaced numbers over a specified interval.
# Returns `num` evenly spaced samples, calculated over the interval [`start`, `stop`].
#The endpoint of the interval can optionally be excluded.
np.linspace(1,50,10) #The 10 in this the number of values outputted.

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [12]:
# The info method is used to get information for a function, class or module
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [13]:
# np.add adds values element-wise.
np.add(4,8)

12

In [20]:
# np.absolute method calculates the absolute value element-wise
x = np.arange(2,25)
x
np.abs(x)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24])

In [21]:
#np.max gets the largest number from given values
np.max(x)

24

In [23]:
# np.max gets the smallest number from given values.
np.min(x)

2

In [25]:
# compute the  weighted average along the specified axis
np.average(x)

13.0

In [26]:
# returns a true division of inputs, element-wise.
np.divide(10,2)

5.0

In [27]:
# Return a new array of given shape and type, without initializing entries.
np.empty(2)

array([ 1., 50.])

In [28]:
# np.sort returns a sorted copy of an array
arr = np.array([20, 10, 50, 15, 67])
np.sort(arr)

array([10, 15, 20, 50, 67])

In [33]:
# np.zero returns the indices of the elements that are non-zero.
x = np.array([[1,9,0], [0,39,89]])
np.nonzero(x < 1)

(array([0, 1], dtype=int64), array([2, 0], dtype=int64))

In [34]:
a1 = np.array([[2,3], [4,5]])
a2 = np.array([[7,8], [9,6]])

In [35]:
# np.vstack stacks arrays in sequence vertically (row wise).
np.vstack((a1, a2))

array([[2, 3],
       [4, 5],
       [7, 8],
       [9, 6]])

In [36]:
# np.hstack stacks arrays in sequence horizontally (column wise).
np.hstack((a1, a2))

array([[2, 3, 7, 8],
       [4, 5, 9, 6]])

In [40]:
# np.hsplit splits an array into multiple sub-arrays horizontally (column-wise).
x = np.arange(2,20)
x
np.hsplit(x,3)

[array([2, 3, 4, 5, 6, 7]),
 array([ 8,  9, 10, 11, 12, 13]),
 array([14, 15, 16, 17, 18, 19])]

In [41]:
# np.sum  returns a sum of array elements over a given axis.
age = np.array([1,2,3,6,8])
np.sum(age)

20

In [44]:
# reshape method returns an array containing the same data with a new shape.
a = np.arange(30)
b = a.reshape((2, -1, 3))
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [45]:
# Join a sequence of arrays along an existing axis.
a = np.array([1,3,4,5])
b = np.array([9,8,7,6])
np.concatenate((a,b))

array([1, 3, 4, 5, 9, 8, 7, 6])

In [47]:
# Return a copy of the array.
c = a.copy()
print(c)

[1 3 4 5]


In [48]:
# Return a copy of the array collapsed into one dimension.
a = np.array([[1,2,3,4], [5,6,7,8]])
a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [1]:
import numpy as np
import pandas as pd

In [2]:
labels = ["a","b","c"]
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {"a":10, "b":20, "c":30}

In [3]:
# Creating a series
pd.Series(data = my_list)

0    10
1    20
2    30
dtype: int64

In [6]:
# Creating a data frame
employees = pd.DataFrame({"Name":["Hilda", "Patience", "Flower"], "Age": [22,23,24], "Salary": [10000, 20000, 40000],})
employees

Name  Age  Salary
0     Hilda   22   10000
1  Patience   23   20000
2    Flower   24   40000

In [7]:
# Find the largest value
employees["Age"].max()

24

In [8]:
# Find the smallest value
employees["Salary"].min()

10000

In [9]:
# Generate descriptive statistics.
employees.describe()

Age        Salary
count   3.0      3.000000
mean   23.0  23333.333333
std     1.0  15275.252317
min    22.0  10000.000000
25%    22.5  15000.000000
50%    23.0  20000.000000
75%    23.5  30000.000000
max    24.0  40000.000000

In [11]:
# Return the dtypes in the DataFrame.
employees.dtypes

Name      object
Age        int64
Salary     int64
dtype: object

In [34]:
# Returns required number of rows
employees.head(2)

Name  Age  Salary
0     Hilda   22   10000
1  Patience   23   20000

In [13]:
# Print a concise summary of a DataFrame.
employees.info

<bound method DataFrame.info of        Name  Age  Salary
0     Hilda   22   10000
1  Patience   23   20000
2    Flower   24   40000>

In [15]:
# Calculating the mean of values in a data frame
employees["Age"].mean()

23.0

In [16]:
# Calculating the median of values in a data frame
employees["Salary"].median()

20000.0

In [18]:
# Changes a string to lower case
employees["Name"].str.lower()

0       hilda
1    patience
2      flower
Name: Name, dtype: object

In [19]:
# Changes a string to the capital case
employees["Name"].str.capitalize()

0       Hilda
1    Patience
2      Flower
Name: Name, dtype: object

In [20]:
# looks up a value and returns true or false if the value is there or not
employees["Name"].str.contains("Crestable")

0    False
1    False
2    False
Name: Name, dtype: bool

In [21]:
# Finds the number of characters in a string
employees["Name"].str.len()

0    5
1    8
2    6
Name: Name, dtype: int64

In [22]:
# Returns the index with the longest characters
employees["Name"].str.len().idxmax()

1

In [24]:
# Using an index
my_sisters = pd.Series([1,2,3,4], index = ["Mercy", "Crestable", "Grace", "Pearl"])
my_sisters


Mercy        1
Crestable    2
Grace        3
Pearl        4
dtype: int64

In [25]:
# adding two series
my_marks1 = pd.Series([85,90,98], index = ["Machine learning", "Excel", "Python"])
my_marks2 = pd.Series([93,95,87], index = ["Machine learning", "Excel", "Python"] )
my_marks1 + my_marks2

Machine learning    178
Excel               185
Python              185
dtype: int64

In [26]:
from numpy.random import randn
np.random.seed(100)

In [27]:
np.random.seed()

In [28]:
# arranges data into rows and columns
df = pd.DataFrame(randn(5,4), index = 'A B C D E '.split(), columns = 'W X Y Z'.split())
df

W         X         Y         Z
A  2.866292 -0.004314 -0.005980  0.711362
B -0.740142 -0.205972  0.444164  0.308198
C -1.540652  1.011264  2.766935 -1.962165
D  0.113525  1.537141 -1.106882 -0.187346
E  1.002769 -1.851140  0.221705 -1.461180

In [29]:
# Remove a column from a data frame
new = df.drop("Y", axis = 1)
new

W         X         Z
A  2.866292 -0.004314  0.711362
B -0.740142 -0.205972  0.308198
C -1.540652  1.011264 -1.962165
D  0.113525  1.537141 -0.187346
E  1.002769 -1.851140 -1.461180

In [31]:
# locks up and index and returns its elements
new.loc["B"]

W   -0.740142
X   -0.205972
Z    0.308198
Name: B, dtype: float64

In [33]:
# Use of indexing to look up a value
new.iloc[2]

W   -1.540652
X    1.011264
Z   -1.962165
Name: C, dtype: float64